// Code generated by protoc-gen-go. DO NOT EDIT.
// source: yamq.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Protocol struct {
	Method               *string  `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Queue                *string  `protobuf:"bytes,2,opt,name=queue" json:"queue,omitempty"`
	PubType              *string  `protobuf:"bytes,3,opt,name=pub_type,json=pubType" json:"pub_type,omitempty"`
	RoutingKey           *string  `protobuf:"bytes,4,opt,name=routing_key,json=routingKey" json:"routing_key,omitempty"`
	Msgid                *string  `protobuf:"bytes,5,opt,name=msgid" json:"msgid,omitempty"`
	Ack                  *bool    `protobuf:"varint,6,opt,name=ack" json:"ack,omitempty"`
	Body                 *string  `protobuf:"bytes,10,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Protocol) Reset()         { *m = Protocol{} }
func (m *Protocol) String() string { return proto.CompactTextString(m) }
func (*Protocol) ProtoMessage()    {}
func (*Protocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_e37599cf7dbc8a2f, []int{0}
}

func (m *Protocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Protocol.Unmarshal(m, b)
}
func (m *Protocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Protocol.Marshal(b, m, deterministic)
}
func (m *Protocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Protocol.Merge(m, src)
}
func (m *Protocol) XXX_Size() int {
	return xxx_messageInfo_Protocol.Size(m)
}
func (m *Protocol) XXX_DiscardUnknown() {
	xxx_messageInfo_Protocol.DiscardUnknown(m)
}

var xxx_messageInfo_Protocol proto.InternalMessageInfo

func (m *Protocol) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Protocol) GetQueue() string {
	if m != nil && m.Queue != nil {
		return *m.Queue
	}
	return ""
}

func (m *Protocol) GetPubType() string {
	if m != nil && m.PubType != nil {
		return *m.PubType
	}
	return ""
}

func (m *Protocol) GetRoutingKey() string {
	if m != nil && m.RoutingKey != nil {
		return *m.RoutingKey
	}
	return ""
}

func (m *Protocol) GetMsgid() string {
	if m != nil && m.Msgid != nil {
		return *m.Msgid
	}
	return ""
}

func (m *Protocol) GetAck() bool {
	if m != nil && m.Ack != nil {
		return *m.Ack
	}
	return false
}

func (m *Protocol) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Protocol)(nil), "pb.Protocol")
}

func init() { proto.RegisterFile("yamq.proto", fileDescriptor_e37599cf7dbc8a2f) }

var fileDescriptor_e37599cf7dbc8a2f = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8c, 0xcd, 0xae, 0x82, 0x30,
	0x10, 0x85, 0x53, 0xfe, 0x2e, 0x77, 0xdc, 0x98, 0x89, 0x31, 0xe3, 0x4a, 0xe2, 0x8a, 0x95, 0x2f,
	0xe2, 0xc6, 0x10, 0xf7, 0x84, 0xc2, 0x04, 0x09, 0x62, 0x0b, 0xb6, 0x8b, 0xbe, 0x95, 0x8f, 0x68,
	0x5a, 0xd8, 0x9d, 0xef, 0x9c, 0x93, 0x0f, 0xc0, 0x35, 0xd3, 0x7c, 0xd5, 0x8b, 0x32, 0x0a, 0x23,
	0x2d, 0x2f, 0x5f, 0x01, 0xf9, 0xdd, 0x53, 0xab, 0x5e, 0x78, 0x84, 0x6c, 0x62, 0xf3, 0x54, 0x1d,
	0x89, 0x42, 0x94, 0xff, 0xd5, 0x46, 0x78, 0x80, 0x74, 0xb6, 0x6c, 0x99, 0xa2, 0x50, 0xaf, 0x80,
	0x27, 0xc8, 0xb5, 0x95, 0xb5, 0x71, 0x9a, 0x29, 0x0e, 0xc3, 0x9f, 0xb6, 0xf2, 0xe1, 0x34, 0xe3,
	0x19, 0x76, 0x8b, 0xb2, 0x66, 0x78, 0xf7, 0xf5, 0xc8, 0x8e, 0x92, 0xb0, 0xc2, 0x56, 0xdd, 0xd8,
	0x79, 0xe3, 0xf4, 0xe9, 0x87, 0x8e, 0xd2, 0xd5, 0x18, 0x00, 0xf7, 0x10, 0x37, 0xed, 0x48, 0x59,
	0x21, 0xca, 0xbc, 0xf2, 0x11, 0x11, 0x12, 0xa9, 0x3a, 0x47, 0x10, 0x6e, 0x21, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xa3, 0xd8, 0xe0, 0x63, 0xc3, 0x00, 0x00, 0x00,
}
